-
  name: Test
  become: yes
  become_user: root
  become_method: sudo
  hosts: ubuntu*:!TSTGEC01:!TSTMAARCHWEB01:!rhel*:!cent*:!debian*:!windows*:!SNB*:!SPHYNX*:!DMZKOLZEPHIR01
  tasks:
    - name:
      apt:
       update_cache: yes
    - name:
      command: apt list --upgradable
      register: updates
    - debug: var=updates.stdout_lines
