-
  name: Test
  become: yes
  become_user: root
  become_method: sudo
  hosts: ubuntu*:cent*:TSTGEC01:!TSTMAARCHWEB01:!rhel*:!debian*:!windows*:!SNB*:!SPHYNX*:!DMZKOLZEPHIR01
  ignore_unreachable: yes
  tasks:
    - name: Install system updates for centos systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status
      become: true
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"
    - name: Install system updates for ubuntu systems
      apt:
        name: '*'
        state: latest
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"
