-
  name: Test
  become: yes
  become_user: root
  become_method: sudo
  hosts: ubuntu*:!TST
  tasks:
    - name:
      apt:
       update_cache: yes
    - name:
      command: apt list --upgradable
      register: updates
    - debug: var=updates.stdout_lines
