-
  name: Copy files on the servers
  hosts: ubuntu64Guest:!windows8Server64Guest:!windows*:!snb*
  tasks:
    - name: Execute copy
      copy:
        src: /home/osboxes/newfiletocheck
        dest: /tmp
